### ISSUE TITLE
Exception while bouncing banned IP (not output captcha/ban page)

### ISSUE THREAD

**Issue by MaxSH97** [crowdsecurity/cs-wordpress-bouncer#124]
Hello all! :wave:

First of all, I would like to say that Crowdsec is a powerful thing, and this WordPress plugin is a total bomb! :zap:

But, I recently noticed a possible problem with this plugin, in a test, and then in a production environment with plugin version - 1.11.0. The captcha/ban page is not displayed, for example, if add your IP address to Crowdsec decisions manually or use a banned IP address by inserting it into the "Forced test IP" field in "Advanced Settings". It simply passes the banned IP further to the site, instead of displaying the captcha/ban page.

In the logs (prod.log) there is an exception message (captcha):
```
2023-02-06T16:17:18.152008+00:00|300|{"type":"NON_AUTHORIZED_X_FORWARDED_FOR_USAGE","original_ip":"XXX.XXX.XXX.XXX","x_forwarded_for_ip":"type not as expected"}
2023-02-06T16:17:18.167364+00:00|300|{"type":"BAD_VALUE","value":" XXX.XXX.XXX.XXX","scope":"Ip","remediation":"ban","cache":"miss"}
2023-02-06T16:17:18.167583+00:00|200|{"type":"FINAL_REMEDIATION","ip":" XXX.XXX.XXX.XXX","remediation":"ban"}
2023-02-06T16:17:18.169490+00:00|400|{"type":"WP_EXCEPTION_WHILE_BOUNCING","message":"An exception has been thrown during the compilation of a template (\"include(/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/composer/../twig/twig/src/TwigTest.php): failed to open stream: No such file or directory (Error level: 2)\") in \"captcha.html.twig\".","code":0,"file":"/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Environment.php","line":521}
```

And the same for the page with a ban (here briefly, only an exception, everything repeats):
```
2023-02-06T16:27:41.991953+00:00|400|{"type":"WP_EXCEPTION_WHILE_BOUNCING","message":"An exception has been thrown during the compilation of a template (\"include(/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/composer/../twig/twig/src/TwigTest.php): failed to open stream: No such file or directory (Error level: 2)\") in \"ban.html.twig\".","code":0,"file":"/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Environment.php","line":521}
```

debug.log:
```
2023-02-08T16:45:29.912247+00:00|100|{"type":"REST_CLIENT_INIT","base_uri":"http://127.0.0.1:8080","timeout":120,"user_agent":"WordPress CrowdSec Bouncer/v1.11.0"}
2023-02-08T16:45:29.912563+00:00|100|{"type":"API_CLIENT_INIT","user_agent":"WordPress CrowdSec Bouncer/v1.11.0","rest_client":"CrowdSecBouncer\\RestClient\\Curl"}
2023-02-08T16:45:29.913331+00:00|100|{"type":"API_CACHE_INIT","adapter":"Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter","mode":"live","fallback_remediation":"captcha","exp_clean_ips":5,"exp_bad_ips":20,"exp_captcha_flow":86400,"exp_geolocation_result":86400,"warmed_up":"false","geolocation":{"enabled":false,"type":"maxmind","save_result":false,"maxmind":{"database_type":"country","database_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../geolocation/"}}}
2023-02-08T16:45:29.913362+00:00|100|{"type":"BOUNCER_INIT","logger":"Monolog\\Logger","max_remediation_level":1,"configs":{"api_key":"***","auth_type":"api_key","tls_cert_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../tls/","tls_key_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../tls/","tls_verify_peer":false,"tls_ca_cert_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../tls/","api_url":"http://127.0.0.1:8080","use_curl":true,"api_user_agent":"WordPress CrowdSec Bouncer/v1.11.0","api_timeout":120,"debug_mode":true,"disable_prod_log":false,"log_directory_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../logs/","forced_test_ip":"XXX.XXX.XXX.XXX","forced_test_forwarded_ip":"","display_errors":false,"bouncing_level":"flex_bouncing","trust_ip_forward_array":[],"fallback_remediation":"captcha","stream_mode":false,"cache_system":"phpfs","fs_cache_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../.cache","redis_dsn":"","memcached_dsn":"","clean_ip_cache_duration":5,"bad_ip_cache_duration":20,"captcha_cache_duration":86400,"geolocation_cache_duration":86400,"geolocation":{"enabled":false,"type":"maxmind","save_result":false,"maxmind":{"database_type":"country","database_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../geolocation/"}},"max_remediation_level":"captcha","excluded_uris":[]}}
2023-02-08T16:45:29.913409+00:00|300|{"type":"NON_AUTHORIZED_X_FORWARDED_FOR_USAGE","original_ip":"XXX.XXX.XXX.XXX","x_forwarded_for_ip":"type not as expected"}
2023-02-08T16:45:29.913651+00:00|100|{"type":"START_IP_CHECK","ip":"XXX.XXX.XXX.XXX"}
2023-02-08T16:45:29.913799+00:00|300|{"type":"BAD_VALUE","value":"XXX.XXX.XXX.XXX","scope":"Ip","remediation":"ban","cache":"hit"}
2023-02-08T16:45:29.913907+00:00|200|{"type":"FINAL_REMEDIATION","ip":"XXX.XXX.XXX.XXX","remediation":"ban"}
2023-02-08T16:45:29.914806+00:00|400|{"type":"WP_EXCEPTION_WHILE_BOUNCING","message":"An exception has been thrown during the compilation of a template (\"include(/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/composer/../twig/twig/src/TwigTest.php): failed to open stream: No such file or directory (Error level: 2)\") in \"captcha.html.twig\".","code":0,"file":"/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Environment.php","line":521}
```

If enable WP_DEBUG and "Enable errors display":
```
Fatal error: Uncaught CrowdSecBouncer\BouncerException: include(/var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/composer/../twig/twig/src/TwigTest.php): failed to open stream: No such file or directory (Error level: 2) in /var/www/<site_dir>/wp-content/plugins/crowdsec/inc/Bounce.php:319
Stack trace:
#0 /var/www/<site_dir>/wp-content/plugins/all-in-one-seo-pack/vendor/composer/ClassLoader.php(571): Bounce->{closure}()
#1 /var/www/<site_dir>/wp-content/plugins/all-in-one-seo-pack/vendor/composer/ClassLoader.php(571): include()
#2 /var/www/<site_dir>/wp-content/plugins/all-in-one-seo-pack/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Extension/CoreExtension.php(243): spl_autoload_call()
#5 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/ExtensionSet.php(431): Twig\Extension\CoreExtension->getTests()
#6 /var/www/<site_dir>/wp-con
in /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Environment.php on line 521
```

This exception appears in versions 1.10.0 and 1.11.0. In the test environment, deactivation of all other plugins was tried, and for version 1.11.0, a test was made in a clean installation of WordPress. The result is the same.

This TwigTest.php file is missing from the plugin directory.

Version 1.9.0 displays pages with captcha/ban when banned or manually "Forced test IP" without any problems.

Also, I have already tried plugin version 2.0.0 on a clean installation of WordPress. The problem still remains. But, in the logs there seems to be no information about the error (debug.log):
```
2023-02-09T15:59:08.230416+00:00|100|Instantiate client|{"type":"CLIENT_INIT","configs":{"api_key":"***","auth_type":"api_key","tls_cert_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../tls/","tls_key_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../tls/","tls_verify_peer":false,"tls_ca_cert_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../tls/","api_url":"http://127.0.0.1:8080","api_timeout":120,"user_agent_version":"v2.0.0","user_agent_suffix":"WordPress"}}
2023-02-09T15:59:08.231299+00:00|100|Instantiate cache|{"type":"CACHE_INIT","configs":{"fs_cache_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../.cache"},"adapter":"Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter"}
2023-02-09T15:59:08.231581+00:00|100|Instantiate remediation engine|{"type":"REM_INIT","configs":{"fallback_remediation":"captcha","stream_mode":false,"clean_ip_cache_duration":60,"bad_ip_cache_duration":120,"geolocation":{"enabled":false,"type":"maxmind","cache_duration":86400,"maxmind":{"database_type":"country","database_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../geolocation/"}},"ordered_remediations":["ban","captcha","bypass"]},"cache":"CrowdSec\\RemediationEngine\\CacheStorage\\PhpFiles"}
2023-02-09T15:59:08.231894+00:00|100|Instantiate bouncer|{"type":"BOUNCER_INIT","logger":"CrowdSec\\Common\\Logger\\FileLog","remediation":"CrowdSec\\RemediationEngine\\LapiRemediation","configs":{"use_curl":true,"debug_mode":true,"disable_prod_log":false,"log_directory_path":"/var/www/<site_dir>/wp-content/plugins/crowdsec/inc/../logs/","forced_test_ip":"XXX.XXX.XXX.XXX","forced_test_forwarded_ip":"","display_errors":true,"bouncing_level":"normal_bouncing","trust_ip_forward_array":[],"cache_system":"phpfs","captcha_cache_duration":86400,"hide_mentions":false,"custom_css":"","excluded_uris":[]}}
2023-02-09T15:59:08.232324+00:00|100|Cache result|{"type":"LAPI_REM_CACHED_DECISIONS","ip":"XXX.XXX.XXX.XXX","result":"miss"}
2023-02-09T15:59:08.232351+00:00|100|Now processing a bouncer request|{"type":"BOUNCER_CLIENT_REQUEST","method":"GET","endpoint":"/v1/decisions","parameters":{"ip":"XXX.XXX.XXX.XXX"}}
2023-02-09T15:59:08.239015+00:00|100|Decisions have been sorted by priority|{"type":"REM_SORTED_DECISIONS","decisions":[{"0":"ban","1":1675958468,"2":"CAPI-ban-ip-XXX.XXX.XXX.XXX","priority":0}]}
```

If enabled, "Enable errors display" (without WP_DEBUG), then almost immediately a letter arrives with a plugin exception from WordPress:
```
An error with type E_ERROR occurred on line 35 of the file /var/www/<site_dir>/wp-content/plugins/crowdsec/inc/bounce-current-ip.php.
Error message: Uncaught Error: Class 'Twig\TwigTest' not found in /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Extension/CoreExtension.php:245
Stack trace:
#0 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/ExtensionSet.php(448): Twig\Extension\CoreExtension->getTests()
#1 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/ExtensionSet.php(428): Twig\ExtensionSet->initExtension()
#2 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/ExtensionSet.php(399): Twig\ExtensionSet->initExtensions()
#3 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Environment.php(817): Twig\ExtensionSet->getUnaryOperators()
#4 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Lexer.php(457): Twig\Environment->getUnaryOperators()
#5 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Lexer.php(108): Twig\Lexer->getOperatorRegex()
#6 /var/www/<site_dir>/wp-content/plugins/crowdsec/vendor/twig/twig/src/Envi
```

Additionally, I provide information about the production environment:
[wordpress-prod.txt](https://github.com/crowdsecurity/cs-wordpress-bouncer/files/10700984/wordpress-prod.txt)

Server OS:
```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Debian 11.6
```

Crowdsec:
```
2023/02/10 00:50:32 version: v1.4.5-debian-pragmatic-a9a2186a76af63551352aa3bc296bdbe80ca4893
2023/02/10 00:50:32 Codename: alphaga
2023/02/10 00:50:32 BuildDate: 2023-01-19_15:06:57
2023/02/10 00:50:32 GoVersion: 1.19.2
2023/02/10 00:50:32 Platform: linux
2023/02/10 00:50:32 Constraint_parser: >= 1.0, <= 2.0
2023/02/10 00:50:32 Constraint_scenario: >= 1.0, < 3.0
2023/02/10 00:50:32 Constraint_api: v1
2023/02/10 00:50:32 Constraint_acquis: >= 1.0, < 2.0
```

Plugin settings that are changed from default in production environment:
- Use cURL to call Local API - Yes
- Local API request timeout - 10 sec
- Bouncing level - Flex bouncing
- Public website only - No
- Theme customization - Messages and custom CSS code
- Captcha flow cache lifetime - 604800 sec
- Geolocation cache lifetime - 604800 sec

I'm sorry to face this problem, but I'm ready to help :slightly_smiling_face:

I hope that the problem will be confirmed by you.
If you need any additional information, tests on this issue, I am always ready to provide and help with this.

Thank you in advance!

Best regards,
Maksim Strekalovskikh

**Comment by julienloizelet** [comment]
Hi @MaxSH97, thanks for your message.

Indeed, it seems that the `TwigTest.php` file is missing in the zip file.

I will try to debug this asap.

**Comment by julienloizelet** [comment]
Hi @MaxSH97, I just published a `2.0.1` release with a fix. 
Could you test it to see if it works as expected now ? 

For information, the `TwigTest.php` files was present on the source of this repo (https://github.com/crowdsecurity/cs-wordpress-bouncer/blob/v2.0.0/vendor/twig/twig/src/TwigTest.php) but the release process is using a `.distignore` file to create the zip and it was removing all files ending by `Test.php` (https://github.com/crowdsecurity/cs-wordpress-bouncer/blob/v2.0.0/.distignore#L34).

I will add a test GitHub action to test the final release zip (and not only the sources, as it is currently the case). Thus, it should help to avoid such mishaps.

Thanks again for reporting this issue.

**Comment by MaxSH97** [comment]
Hello, @julienloizelet!

Thank you very much for checking and making a fix very quickly!

During this day I will test this fix on a test environment, and I will return with the results of the test.

**Comment by MaxSH97** [comment]
@julienloizelet I'm back with test results on a test environment.

`2.0.1` now works as expected. Ban and captcha walls are displayed without problems.

I have no questions or doubts.
I'll update plugin in production environment right now.

Thank you very much again for the response and the quick fix!
I'm closing this issue.
Have a nice day! :wink:
